export const CHECKLIST_ITEMS = [
    { id: "gbm_att", label: "GBM Attendance Book", category: "Documents" },
    { id: "gbm_min", label: "GBM Minutes Book", category: "Documents" },
    { id: "board_att", label: "Board Meeting Attendance Book", category: "Documents" },
    { id: "board_min", label: "Board Meeting Minutes Book", category: "Documents" },
    { id: "noti_rec", label: "Meeting Notification Records (e-copies)", category: "Documents" },
    { id: "bio_forms", label: "Member's Bio data forms (e-copies)", category: "Documents" },
    { id: "pres_in", label: "President's Incoming File (e-copies)", category: "Documents" },
    { id: "pres_out", label: "President's Outgoing File (e-copies)", category: "Documents" },
    { id: "sec_in", label: "Secretary's Incoming File (e-copies)", category: "Documents" },
    { id: "sec_out", label: "Secretary's Outgoing File (e-copies)", category: "Documents" },
    { id: "mon_rep", label: "Monthly Report Copies (e-copies)", category: "Documents" },
    { id: "mon_ack", label: "Monthly Report Acknowledgement Letters", category: "Documents" },
    { id: "bank_pass", label: "Bank Passbook/Bank Account Statement", category: "Documents" },
    { id: "receipt_book", label: "Receipt Book", category: "Documents" },
    { id: "bills", label: "Bills and Receipts (e-copies/Hard copies)", category: "Documents" },
    { id: "club_acc", label: "Club Accounts Book", category: "Documents" },
    { id: "half_year", label: "Duly passed half yearly account statement", category: "Documents" },
    { id: "pr_file", label: "Public Relations File (e-copies)", category: "Documents" },
    { id: "bulletin", label: "Club Bulletin Copies (e-copies)", category: "Documents" },
    { id: "dist_prio", label: "District Priority Project File (e-copies)", category: "Documents" },
    { id: "ave_files", label: "Avenue Files (e-copies)", category: "Documents" },
    { id: "ann_plan", label: "Annual Planner & Budget (e-copies)", category: "Documents" },
    { id: "dist_train", label: "District Trainer(s) Report (e-copies)", category: "Documents" },
    { id: "partners", label: "Partners in Service File (e-copies)", category: "Documents" },

    { id: "charter", label: "Club Charter", category: "Properties" },
    { id: "collar", label: "Club President's Collar & Gavel", category: "Properties" },
    { id: "banner", label: "Club Banner", category: "Properties" },
    { id: "social", label: "Club Website/Social Media Handles", category: "Properties" },
    { id: "letterhead", label: "Club Letterhead", category: "Properties" },
    { id: "pins", label: "Club Member's Lapel Pins/ID Cards", category: "Properties" },
    { id: "lh_exch", label: "Letterhead Exchanges", category: "Properties" },
    { id: "bylaw", label: "Adopted Club Bylaw", category: "Properties" },
    { id: "consti", label: "Standard Rotaract Constitution & Policies", category: "Properties" },
    { id: "awards", label: "District/Group Awards", category: "Properties" },
    { id: "scrapbook", label: "Previous Year(s) Scrapbook", category: "Properties" },
    { id: "prev_acc", label: "Previous Year Account Statement", category: "Properties" },
    { id: "past_list", label: "List of Past Presidents & Secretaries", category: "Properties" },
];

export const SCORING_CRITERIA = [
    { id: "inst", label: "Club installation", maxPoints: 4, type: "input" },
    { id: "orient", label: "Club Orientation", maxPoints: 4, type: "input" },
    { id: "dist_dues", label: "District Membership dues", maxPoints: 4, type: "input" },
    { id: "plan", label: "Annual Planner & Budget", maxPoints: 4, type: "input" },
    { id: "mon_rep", label: "Monthly Report (12 months x 1pt)", maxPoints: 12, type: "input" },
    { id: "ack_let", label: "Acknowledgement Letter (12 months x 1pt)", maxPoints: 12, type: "input" },
    { id: "bulletin", label: "Club Bulletin/Newsletter (12 months x 2pt)", maxPoints: 24, type: "input" },
    { id: "dist_att", label: "65% Attendance in District Events", maxPoints: 6, type: "input" },
    { id: "joint_proj", label: "Joint Projects (6 items x 1pt)", maxPoints: 6, type: "input" },
    { id: "ri_dues", label: "RI Dues", maxPoints: 3, type: "input" },
    { id: "ri_week", label: "World Rotaract Week Celebration", maxPoints: 3, type: "input" },
    { id: "dist_prio", label: "District Priority Projects", maxPoints: 10, type: "input" },
    { id: "drr_visit", label: "DRR Official Visit", maxPoints: 5, type: "input" },
    { id: "scrap_sub", label: "Scrap Book Submission", maxPoints: 3, type: "input" },
    { id: "rot_meet", label: "Attending Rotary Meetings", maxPoints: 4, type: "input" },
    { id: "club_ex", label: "Club Excellence award", maxPoints: 2, type: "input" },

    // Value Added
    { id: "joint_int", label: "Joint Project with Interact", maxPoints: 2, type: "input" },
    { id: "joint_inner", label: "Joint Project with Inner wheel", maxPoints: 2, type: "input" },
    { id: "target_rot", label: "Volunteering for Rotary events", maxPoints: 3, type: "input" },
    { id: "dist_init", label: "District initiatives support", maxPoints: 6, type: "input" },
    { id: "rlc_usage", label: "Rotary Learning Centre usage", maxPoints: 3, type: "input" },
    { id: "prom_pr", label: "Promoting PR", maxPoints: 3, type: "input" },
    { id: "penta_id", label: "Penta ID Sessions", maxPoints: 5, type: "input" },
    { id: "idye", label: "Participation in Incoming/Outgoing IDYE", maxPoints: 4, type: "input" },
    { id: "rotasia", label: "Participation in Rotasia 2026", maxPoints: 2, type: "input" },
    { id: "host_dist", label: "Hosting District Event", maxPoints: 2, type: "input" },
    { id: "100_mem", label: "Reporting 100% Membership in RI", maxPoints: 3, type: "input" },
    { id: "mem_growth", label: "Membership Growth (Max 3)", maxPoints: 3, type: "input" },
    { id: "social_med", label: "Actively Maintaining Club's Social Media", maxPoints: 4, type: "input" },
    { id: "blood_cell", label: "Volunteering for Rotaract Blood donor cell", maxPoints: 1, type: "input" },
    { id: "cust_proj", label: "Sustainability of Projects", maxPoints: 5, type: "input" },
    { id: "trf", label: "TRF Contribution", maxPoints: 5, type: "input" },
    { id: "giving_cert", label: "Rotaract Giving Certificate", maxPoints: 5, type: "input" },
];

export const getEfficiencyStatus = (points: number) => {
    if (points >= 96) return "HYPERACTIVE";
    if (points >= 76) return "SUPERACTIVE";
    if (points >= 51) return "ACTIVE";
    return "NONE";
};
